<h1 class="title"><?php print $data['title'] ?></h1>

<!-- All the pizza items will be generated by JS in this container -->
<table id="admin-orders-table-container"></table>


<!-- Update Modal (Popup)-->
<?php if (isset($data['forms']['status'])): ?>
    <div id="update-modal" class="modal">
        <div class="wrapper">
            <span class="close">&times;</span>
            <?php print $data['forms']['status']; ?>
        </div>
    </div>
<?php endif; ?>

<?php //foreach ($data['links'] as $link): ?>
<!--    --><?php //print $link; ?>
<?php //endforeach; ?>